
name: Build and deploy API

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          envkey_USER_DASHBOARD: ${{ secrets.USER_DASHBOARD }}
          envkey_PASSWORD_DASHBOARD: ${{ secrets.PASSWORD_DASHBOARD }}
          envkey_PASSWORD_MYSQL: ${{ secrets.PASSWORD_MYSQL }}
          directory: /
          file_name: .env.local
          fail_on_empty: false
          sort_keys: false
      
      - name: Deploy serverless
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-3'
          SOURCE_DIR: 'dist'